# Generated by Django 2.2.12 on 2020-06-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restreklama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restreklama.CarType')),
            ],
        ),
    ]
