# Generated by Django 2.2.12 on 2020-06-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restreklama', '0003_categoryforcar_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemReact',
        ),
    ]
