# Generated by Django 2.0.1 on 2019-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('brand', models.IntegerField(default=0)),
                ('title', models.CharField(default=0, max_length=400)),
                ('text', models.CharField(default=0, max_length=400)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
