# Generated by Django 2.2.12 on 2020-06-01 13:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='Name', max_length=250)),
                ('image', models.ImageField(default='profile/none/no-img.jpg', upload_to='profile/')),
                ('tel', models.CharField(default=0, max_length=400)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.IntegerField(default=0)),
                ('name', models.CharField(default=0, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default=0, max_length=400)),
                ('text', models.TextField(blank=True, default=0)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.IntegerField(blank=True, choices=[(1, 'сом'), (2, '$'), (3, 'руб')], default=1)),
                ('city', models.IntegerField(blank=True, choices=[(1, 'Чуй'), (2, 'Ош'), (3, 'Джалал-Абад'), (4, 'Ыссык Кол'), (5, 'Нарын'), (6, 'Талас'), (7, 'Баткен')], default=1)),
                ('year', models.IntegerField(blank=True, default=2000)),
                ('car_pic', models.ImageField(default='none/no-img.jpg', upload_to='')),
                ('car_pic2', models.ImageField(default='none/no-img.jpg', upload_to='')),
                ('car_pic3', models.ImageField(default='none/no-img.jpg', upload_to='')),
                ('brand', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_requests_created', to='cars.Brand')),
                ('profile', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_add', 'can_add_post'),),
            },
        ),
    ]
