# Generated by Django 2.0.1 on 2019-03-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Car',
        ),
    ]
