# Generated by Django 2.0.1 on 2019-03-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20190306_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': (('can_view_odd_ids', 'can_view_odd_ids'), ('can_view_even_ids', 'can_view_even_ids'))},
        ),
    ]
