# Generated by Django 2.0.1 on 2019-03-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190307_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': (('can_view_odd_ids', 'can_view_odd_ids'), ('can_view_even_ids', 'can_view_even_ids'), ('can_add', 'can_add_post'))},
        ),
    ]
