# Generated by Django 2.0.1 on 2019-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
