# Generated by Django 2.0.1 on 2019-03-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20190308_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': (('can_add', 'can_add_post'),)},
        ),
    ]
